/**
 * Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.
 *
 * Every capability the registry declares, and how long a grant of one lasts.
 *
 * Do not edit. The suite that regenerates this file from the registry fails
 * when the two disagree, so the only way to change what lives here is to
 * change the registry and regenerate.
 * @module
 */

export type CapabilityId =
  | 'host.read'
  | 'host.pair'
  | 'host.forget'
  | 'host.select'
  | 'session.read'
  | 'session.create'
  | 'session.message'
  | 'session.cancel'
  | 'session.open'
  | 'tailnet.read'
  | 'tailnet.connect'
  | 'tailnet.forget'
  | 'shell.navigate'

type SubjectKind = 'device' | 'host'

/** One declared capability, and how long a grant of it stays spendable. */
export interface CapabilityDescriptor {
  readonly id: CapabilityId
  readonly subject: SubjectKind
  readonly ttlSeconds: number
}

/** Every declared capability, by id. */
export const CAPABILITIES: Record<CapabilityId, CapabilityDescriptor> = {
  'host.read': { id: 'host.read', subject: 'device', ttlSeconds: 900 },
  'host.pair': { id: 'host.pair', subject: 'device', ttlSeconds: 300 },
  'host.forget': { id: 'host.forget', subject: 'host', ttlSeconds: 300 },
  'host.select': { id: 'host.select', subject: 'device', ttlSeconds: 3600 },
  'session.read': { id: 'session.read', subject: 'host', ttlSeconds: 300 },
  'session.create': { id: 'session.create', subject: 'host', ttlSeconds: 120 },
  'session.message': { id: 'session.message', subject: 'host', ttlSeconds: 120 },
  'session.cancel': { id: 'session.cancel', subject: 'host', ttlSeconds: 120 },
  'session.open': { id: 'session.open', subject: 'host', ttlSeconds: 600 },
  'tailnet.read': { id: 'tailnet.read', subject: 'device', ttlSeconds: 300 },
  'tailnet.connect': { id: 'tailnet.connect', subject: 'device', ttlSeconds: 300 },
  'tailnet.forget': { id: 'tailnet.forget', subject: 'device', ttlSeconds: 300 },
  'shell.navigate': { id: 'shell.navigate', subject: 'device', ttlSeconds: 3600 },
}

/**
 * Whether a string off the wire names a declared capability.
 *
 * A predicate rather than a lookup, so a value read out of a snapshot is
 * narrowed by the compiler and never asserted into a capability it was
 * only hoped to be.
 * @param value - the name to read.
 * @returns whether the name is one the registry declared.
 */
export function isCapabilityId(value: string): value is CapabilityId {
  switch (value) {
    case 'host.read':
    case 'host.pair':
    case 'host.forget':
    case 'host.select':
    case 'session.read':
    case 'session.create':
    case 'session.message':
    case 'session.cancel':
    case 'session.open':
    case 'tailnet.read':
    case 'tailnet.connect':
    case 'tailnet.forget':
    case 'shell.navigate':
      return true
    default:
      return false
  }
}
