/**
 * Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.
 *
 * Do not edit. The suite that regenerates this file from the registry fails
 * when the two disagree, so the only way to change what lives here is to
 * change the registry and regenerate.
 * @module
 */

import type { PickerKey } from '../locales.ts'

export type CapabilityId = 
  | 'host.read'
  | 'host.pair'
  | 'host.forget'
  | 'host.select'
  | 'session.read'
  | 'session.create'
  | 'session.message'
  | 'session.cancel'
  | 'session.open'
  | 'tailnet.read'
  | 'tailnet.connect'
  | 'tailnet.forget'
  | 'shell.navigate'


export type PlacementId = 
  | 'boot'
  | 'return'
  | 'drawer'
  | 'sidebar'
  | 'connection-menu'
  | 'roster-row'
  | 'compose-sheet'
  | 'new-session'
  | 'picker'
  | 'picker-form'
  | 'tailnet'


export type ActionId = 
  | 'boot.retry'
  | 'client.return'
  | 'drawer.toggle'
  | 'drawer.dismiss'
  | 'session.spawn'
  | 'connection.pair'
  | 'connection.repair'
  | 'connection.unpair'
  | 'connection.select'
  | 'session.open'
  | 'session.message'
  | 'session.cancel'
  | 'compose.send'
  | 'compose.steer'
  | 'spawn.create'
  | 'picker.pair'
  | 'picker.tailnet'
  | 'tailnet.connect'
  | 'tailnet.forget'


export type ActionMarker = 
  | 'boot-retry'
  | 'return-fleet'
  | 'drawer'
  | 'drawer-dismiss'
  | 'new-session'
  | 'pair'
  | 'repair'
  | 'unpair'
  | 'select-host'
  | 'row-open'
  | 'row-message'
  | 'row-stop'
  | 'compose-send'
  | 'compose-steer'
  | 'spawn-create'
  | 'pair-submit'
  | 'tailnet'
  | 'tailnet-connect'
  | 'tailnet-forget'


export type AvailabilityId = 'always' | 'hasHosts' | 'hasActiveHost' | 'running' | 'unauthorized' | 'tailnetConnected'

export type SubjectKind = 'device' | 'host'

export type ActionKind = 'query' | 'mutation' | 'navigation' | 'toggle' | 'dialog'

export type ActionPane = 'main' | 'sheet' | 'menu' | 'drawer' | 'none'

/** One declared capability, and how long a grant of it stays spendable. */
export interface CapabilityDescriptor {
  readonly id: CapabilityId
  readonly subject: SubjectKind
  readonly ttlSeconds: number
}

/** One declared action, in full. */
export interface ActionDescriptor {
  readonly id: ActionId
  readonly capability: CapabilityId
  readonly placement: PlacementId
  readonly kind: ActionKind
  readonly pane: ActionPane
  /** The `data-deeptail-action` the control carries, which the suites drive it by. */
  readonly marker: ActionMarker
  /** The predicate that decides whether the control is drawn at all. */
  readonly availability: AvailabilityId
  /** The dictionary key naming the control, absent when its name comes from the row it sits on. */
  readonly labelKey?: PickerKey
  /** The key a toggle carries while it is on. */
  readonly labelKeyOn?: PickerKey
  /** The remote route the action reaches, which the native boundary prices in capabilities. */
  readonly remote?: string
}

/** Every declared capability, by id. */
export const CAPABILITIES: Record<CapabilityId, CapabilityDescriptor> = {
  'host.read': { id: 'host.read', subject: 'device', ttlSeconds: 900 },
  'host.pair': { id: 'host.pair', subject: 'device', ttlSeconds: 300 },
  'host.forget': { id: 'host.forget', subject: 'host', ttlSeconds: 300 },
  'host.select': { id: 'host.select', subject: 'device', ttlSeconds: 3600 },
  'session.read': { id: 'session.read', subject: 'host', ttlSeconds: 300 },
  'session.create': { id: 'session.create', subject: 'host', ttlSeconds: 120 },
  'session.message': { id: 'session.message', subject: 'host', ttlSeconds: 120 },
  'session.cancel': { id: 'session.cancel', subject: 'host', ttlSeconds: 120 },
  'session.open': { id: 'session.open', subject: 'host', ttlSeconds: 600 },
  'tailnet.read': { id: 'tailnet.read', subject: 'device', ttlSeconds: 300 },
  'tailnet.connect': { id: 'tailnet.connect', subject: 'device', ttlSeconds: 300 },
  'tailnet.forget': { id: 'tailnet.forget', subject: 'device', ttlSeconds: 300 },
  'shell.navigate': { id: 'shell.navigate', subject: 'device', ttlSeconds: 3600 },
}

/** Every declared action, by id. */
export const ACTIONS: Record<ActionId, ActionDescriptor> = {
  'boot.retry': { id: 'boot.retry', capability: 'host.read', placement: 'boot', kind: 'query', pane: 'none', marker: 'boot-retry', availability: 'always', labelKey: 'action.retry' },
  'client.return': { id: 'client.return', capability: 'shell.navigate', placement: 'return', kind: 'navigation', pane: 'main', marker: 'return-fleet', availability: 'always', labelKey: 'shell.backToFleet' },
  'drawer.toggle': { id: 'drawer.toggle', capability: 'shell.navigate', placement: 'drawer', kind: 'toggle', pane: 'drawer', marker: 'drawer', availability: 'always', labelKey: 'shell.openSessions', labelKeyOn: 'shell.closeSessions' },
  'drawer.dismiss': { id: 'drawer.dismiss', capability: 'shell.navigate', placement: 'drawer', kind: 'navigation', pane: 'drawer', marker: 'drawer-dismiss', availability: 'always', labelKey: 'shell.closeSessions' },
  'session.spawn': { id: 'session.spawn', capability: 'session.create', placement: 'sidebar', kind: 'dialog', pane: 'sheet', marker: 'new-session', availability: 'hasHosts', labelKey: 'shell.newSession' },
  'connection.pair': { id: 'connection.pair', capability: 'host.pair', placement: 'connection-menu', kind: 'navigation', pane: 'none', marker: 'pair', availability: 'always', labelKey: 'action.pair' },
  'connection.repair': { id: 'connection.repair', capability: 'host.pair', placement: 'connection-menu', kind: 'navigation', pane: 'none', marker: 'repair', availability: 'unauthorized', labelKey: 'shell.repair' },
  'connection.unpair': { id: 'connection.unpair', capability: 'host.forget', placement: 'connection-menu', kind: 'mutation', pane: 'none', marker: 'unpair', availability: 'hasActiveHost', labelKey: 'shell.unpair' },
  'connection.select': { id: 'connection.select', capability: 'host.select', placement: 'connection-menu', kind: 'navigation', pane: 'main', marker: 'select-host', availability: 'always' },
  'session.open': { id: 'session.open', capability: 'session.open', placement: 'roster-row', kind: 'navigation', pane: 'main', marker: 'row-open', availability: 'always', remote: 'session/list' },
  'session.message': { id: 'session.message', capability: 'session.message', placement: 'roster-row', kind: 'dialog', pane: 'sheet', marker: 'row-message', availability: 'always', labelKey: 'sessions.messageAction' },
  'session.cancel': { id: 'session.cancel', capability: 'session.cancel', placement: 'roster-row', kind: 'mutation', pane: 'main', marker: 'row-stop', availability: 'running', labelKey: 'sessions.stop', remote: 'session/cancel' },
  'compose.send': { id: 'compose.send', capability: 'session.message', placement: 'compose-sheet', kind: 'mutation', pane: 'sheet', marker: 'compose-send', availability: 'always', labelKey: 'chat.send', remote: 'session/prompt' },
  'compose.steer': { id: 'compose.steer', capability: 'session.message', placement: 'compose-sheet', kind: 'mutation', pane: 'sheet', marker: 'compose-steer', availability: 'always', labelKey: 'chat.steer', remote: 'session/prompt' },
  'spawn.create': { id: 'spawn.create', capability: 'session.create', placement: 'new-session', kind: 'mutation', pane: 'sheet', marker: 'spawn-create', availability: 'always', remote: 'session/create' },
  'picker.pair': { id: 'picker.pair', capability: 'host.pair', placement: 'picker-form', kind: 'mutation', pane: 'none', marker: 'pair-submit', availability: 'always' },
  'picker.tailnet': { id: 'picker.tailnet', capability: 'tailnet.read', placement: 'picker', kind: 'navigation', pane: 'none', marker: 'tailnet', availability: 'always', labelKey: 'tailnet.action' },
  'tailnet.connect': { id: 'tailnet.connect', capability: 'tailnet.connect', placement: 'tailnet', kind: 'mutation', pane: 'none', marker: 'tailnet-connect', availability: 'always', labelKey: 'tailnet.connect' },
  'tailnet.forget': { id: 'tailnet.forget', capability: 'tailnet.forget', placement: 'tailnet', kind: 'mutation', pane: 'none', marker: 'tailnet-forget', availability: 'tailnetConnected', labelKey: 'tailnet.disconnect' },
}

/** Every declared action, in registry order. */
export const ACTION_LIST: readonly ActionDescriptor[] = [ACTIONS['boot.retry'], ACTIONS['client.return'], ACTIONS['drawer.toggle'], ACTIONS['drawer.dismiss'], ACTIONS['session.spawn'], ACTIONS['connection.pair'], ACTIONS['connection.repair'], ACTIONS['connection.unpair'], ACTIONS['connection.select'], ACTIONS['session.open'], ACTIONS['session.message'], ACTIONS['session.cancel'], ACTIONS['compose.send'], ACTIONS['compose.steer'], ACTIONS['spawn.create'], ACTIONS['picker.pair'], ACTIONS['picker.tailnet'], ACTIONS['tailnet.connect'], ACTIONS['tailnet.forget']]

/** Every declared action id, in registry order. */
export const ACTION_IDS: readonly ActionId[] = ['boot.retry', 'client.return', 'drawer.toggle', 'drawer.dismiss', 'session.spawn', 'connection.pair', 'connection.repair', 'connection.unpair', 'connection.select', 'session.open', 'session.message', 'session.cancel', 'compose.send', 'compose.steer', 'spawn.create', 'picker.pair', 'picker.tailnet', 'tailnet.connect', 'tailnet.forget']

/** Every declared capability id, in registry order. */
export const CAPABILITY_IDS: readonly CapabilityId[] = ['host.read', 'host.pair', 'host.forget', 'host.select', 'session.read', 'session.create', 'session.message', 'session.cancel', 'session.open', 'tailnet.read', 'tailnet.connect', 'tailnet.forget', 'shell.navigate']

/**
 * Whether a string off the wire names a declared capability.
 *
 * A predicate rather than a lookup, so a value read out of a snapshot is
 * narrowed by the compiler and never asserted into a capability it was
 * only hoped to be.
 * @param value - the name to read.
 * @returns whether the name is one the registry declared.
 */
export function isCapabilityId(value: string): value is CapabilityId {
  switch (value) {
    case 'host.read':
    case 'host.pair':
    case 'host.forget':
    case 'host.select':
    case 'session.read':
    case 'session.create':
    case 'session.message':
    case 'session.cancel':
    case 'session.open':
    case 'tailnet.read':
    case 'tailnet.connect':
    case 'tailnet.forget':
    case 'shell.navigate':
      return true
    default:
      return false
  }
}

/**
 * The actions seated in one placement, in registry order.
 * @param placement - the surface to read.
 * @returns the actions seated there.
 */
export function actionsInPlacement(placement: PlacementId): readonly ActionDescriptor[] {
  return ACTION_LIST.filter((action) => action.placement === placement)
}

/**
 * The actions one capability pays for.
 * @param capability - the capability to read.
 * @returns the actions that cost it.
 */
export function actionsForCapability(capability: CapabilityId): readonly ActionDescriptor[] {
  return ACTION_LIST.filter((action) => action.capability === capability)
}

