/**
 * Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.
 *
 * The types every action is read through, and the lists that walk them.
 *
 * Do not edit. The suite that regenerates this file from the registry fails
 * when the two disagree, so the only way to change what lives here is to
 * change the registry and regenerate.
 * @module
 */

import type { PickerKey } from '../locales.ts'
import { ACTIONS } from './action-table.ts'
import type { CapabilityId } from './capabilities.ts'

export { ACTIONS } from './action-table.ts'
export type { CapabilityId } from './capabilities.ts'
export { CAPABILITIES, isCapabilityId } from './capabilities.ts'

type PlacementId =
  | 'boot'
  | 'return'
  | 'drawer'
  | 'sidebar'
  | 'connection-menu'
  | 'roster-row'
  | 'compose-sheet'
  | 'new-session'
  | 'picker'
  | 'picker-form'
  | 'tailnet'

export type ActionId =
  | 'boot.retry'
  | 'client.return'
  | 'drawer.toggle'
  | 'drawer.dismiss'
  | 'session.spawn'
  | 'connection.pair'
  | 'connection.repair'
  | 'connection.unpair'
  | 'connection.select'
  | 'session.open'
  | 'session.message'
  | 'session.cancel'
  | 'compose.send'
  | 'compose.steer'
  | 'spawn.create'
  | 'picker.pair'
  | 'picker.tailnet'
  | 'tailnet.connect'
  | 'tailnet.forget'

export type ActionMarker =
  | 'boot-retry'
  | 'return-fleet'
  | 'drawer'
  | 'drawer-dismiss'
  | 'new-session'
  | 'pair'
  | 'repair'
  | 'unpair'
  | 'select-host'
  | 'row-open'
  | 'row-message'
  | 'row-stop'
  | 'compose-send'
  | 'compose-steer'
  | 'spawn-create'
  | 'pair-submit'
  | 'tailnet'
  | 'tailnet-connect'
  | 'tailnet-forget'

type AvailabilityId = 'always' | 'hasHosts' | 'hasActiveHost' | 'running' | 'unauthorized' | 'tailnetConnected'

type ActionKind = 'query' | 'mutation' | 'navigation' | 'toggle' | 'dialog'

type ActionPane = 'main' | 'sheet' | 'menu' | 'drawer' | 'none'

/** One declared action, in full. */
export interface ActionDescriptor {
  readonly id: ActionId
  readonly capability: CapabilityId
  readonly placement: PlacementId
  readonly kind: ActionKind
  readonly pane: ActionPane
  /** The `data-deeptail-action` the control carries, which the suites drive it by. */
  readonly marker: ActionMarker
  /** The predicate that decides whether the control is drawn at all. */
  readonly availability: AvailabilityId
  /** The dictionary key naming the control, absent when its name comes from the row it sits on. */
  readonly labelKey?: PickerKey
  /** The key a toggle carries while it is on. */
  readonly labelKeyOn?: PickerKey
  /** The remote route the action reaches, which the native boundary prices in capabilities. */
  readonly remote?: string
}

/** Every declared action, in registry order. */
export const ACTION_LIST: readonly ActionDescriptor[] = [
  ACTIONS['boot.retry'],
  ACTIONS['client.return'],
  ACTIONS['drawer.toggle'],
  ACTIONS['drawer.dismiss'],
  ACTIONS['session.spawn'],
  ACTIONS['connection.pair'],
  ACTIONS['connection.repair'],
  ACTIONS['connection.unpair'],
  ACTIONS['connection.select'],
  ACTIONS['session.open'],
  ACTIONS['session.message'],
  ACTIONS['session.cancel'],
  ACTIONS['compose.send'],
  ACTIONS['compose.steer'],
  ACTIONS['spawn.create'],
  ACTIONS['picker.pair'],
  ACTIONS['picker.tailnet'],
  ACTIONS['tailnet.connect'],
  ACTIONS['tailnet.forget'],
]

/** Every declared action id, in registry order. */
export const ACTION_IDS: readonly ActionId[] = [
  'boot.retry',
  'client.return',
  'drawer.toggle',
  'drawer.dismiss',
  'session.spawn',
  'connection.pair',
  'connection.repair',
  'connection.unpair',
  'connection.select',
  'session.open',
  'session.message',
  'session.cancel',
  'compose.send',
  'compose.steer',
  'spawn.create',
  'picker.pair',
  'picker.tailnet',
  'tailnet.connect',
  'tailnet.forget',
]
