/**
 * The action registry, emitted.
 *
 * Two faces come out of one registry. The page compiles against a typed
 * descriptor per action, so a control builder cannot be handed an id nothing
 * declared and a label key cannot name a dictionary entry that does not exist.
 * The native boundary compiles against a route table, so the Rust half prices
 * every remote call in the same capabilities the page spends, from the same
 * bytes.
 *
 * Both are generated, both carry the banner of what wrote them, and a suite
 * regenerates them and compares bytes, so a hand edit is a failing test rather
 * than a silent divergence.
 *
 * @module
 */

import type { ActionRow, Registry } from './action-registry.ts'
import { AVAILABILITY } from './action-registry.ts'

/** The header every generated file carries, naming what wrote it. */
const BANNER = 'Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.'

/**
 * Quote one value for the emitted source.
 * @param value - the string to quote.
 * @returns a single-quoted literal.
 */
function quote(value: string): string {
  return `'${value.replaceAll("'", "\\'")}'`
}

/**
 * The union type one list of names becomes.
 * @param names - the names, in document order.
 * @returns the union, wrapped onto lines when it is long.
 */
function union(names: readonly string[]): string {
  const parts = names.map((name) => quote(name))
  const oneLine = parts.join(' | ')
  return oneLine.length <= 96 ? oneLine : `\n${parts.map((part) => `  | ${part}`).join('\n')}\n`
}

/**
 * One action as the emitted object literal.
 * @param action - the row.
 * @returns the entry, with its trailing comma.
 */
function emitAction(action: ActionRow): string {
  const fields = [
    `id: ${quote(action.id)}`,
    `capability: ${quote(action.capability)}`,
    `placement: ${quote(action.placement)}`,
    `kind: ${quote(action.kind)}`,
    `pane: ${quote(action.pane)}`,
    `marker: ${quote(action.marker)}`,
    `availability: ${quote(action.availability)}`,
  ]
  if (action.labelKey !== undefined) fields.push(`labelKey: ${quote(action.labelKey)}`)
  if (action.labelKeyOn !== undefined) fields.push(`labelKeyOn: ${quote(action.labelKeyOn)}`)
  if (action.remote !== undefined) fields.push(`remote: ${quote(action.remote)}`)
  return `  ${quote(action.id)}: { ${fields.join(', ')} },`
}

/**
 * Emit the page's typed face.
 * @param registry - the validated registry.
 * @returns the contents of `apps/deeptail/src/actions/registry.ts`.
 */
export function emitTypeScript(registry: Registry): string {
  const capabilityIds = registry.capabilities.map((row) => row.id)
  const placementIds = registry.placements.map((row) => row.id)
  const actionIds = registry.actions.map((row) => row.id)
  const markers = registry.actions.map((row) => row.marker)
  return `${[
    `/**\n * ${BANNER}\n *`,
    ' * Do not edit. The suite that regenerates this file from the registry fails',
    ' * when the two disagree, so the only way to change what lives here is to',
    ' * change the registry and regenerate.',
    ' * @module',
    ' */',
    '',
    "import type { PickerKey } from '../locales.ts'",
    '',
    `export type CapabilityId = ${union(capabilityIds)}`,
    '',
    `export type PlacementId = ${union(placementIds)}`,
    '',
    `export type ActionId = ${union(actionIds)}`,
    '',
    `export type ActionMarker = ${union(markers)}`,
    '',
    `export type AvailabilityId = ${AVAILABILITY.map((name) => quote(name)).join(' | ')}`,
    '',
    "export type SubjectKind = 'device' | 'host'",
    '',
    "export type ActionKind = 'query' | 'mutation' | 'navigation' | 'toggle' | 'dialog'",
    '',
    "export type ActionPane = 'main' | 'sheet' | 'menu' | 'drawer' | 'none'",
    '',
    '/** One declared capability, and how long a grant of it stays spendable. */',
    'export interface CapabilityDescriptor {',
    '  readonly id: CapabilityId',
    '  readonly subject: SubjectKind',
    '  readonly ttlSeconds: number',
    '}',
    '',
    '/** One declared action, in full. */',
    'export interface ActionDescriptor {',
    '  readonly id: ActionId',
    '  readonly capability: CapabilityId',
    '  readonly placement: PlacementId',
    '  readonly kind: ActionKind',
    '  readonly pane: ActionPane',
    '  /** The `data-deeptail-action` the control carries, which the suites drive it by. */',
    '  readonly marker: ActionMarker',
    '  /** The predicate that decides whether the control is drawn at all. */',
    '  readonly availability: AvailabilityId',
    '  /** The dictionary key naming the control, absent when its name comes from the row it sits on. */',
    '  readonly labelKey?: PickerKey',
    '  /** The key a toggle carries while it is on. */',
    '  readonly labelKeyOn?: PickerKey',
    '  /** The remote route the action reaches, which the native boundary prices in capabilities. */',
    '  readonly remote?: string',
    '}',
    '',
    '/** Every declared capability, by id. */',
    'export const CAPABILITIES: Record<CapabilityId, CapabilityDescriptor> = {',
    ...registry.capabilities.map(
      (row) =>
        `  ${quote(row.id)}: { id: ${quote(row.id)}, subject: ${quote(row.subject)}, ttlSeconds: ${String(row.ttlSeconds)} },`,
    ),
    '}',
    '',
    '/** Every declared action, by id. */',
    'export const ACTIONS: Record<ActionId, ActionDescriptor> = {',
    ...registry.actions.map(emitAction),
    '}',
    '',
    '/** Every declared action, in registry order. */',
    `export const ACTION_LIST: readonly ActionDescriptor[] = [${actionIds.map((id) => `ACTIONS[${quote(id)}]`).join(', ')}]`,
    '',
    '/** Every declared action id, in registry order. */',
    `export const ACTION_IDS: readonly ActionId[] = [${actionIds.map(quote).join(', ')}]`,
    '',
    '/** Every declared capability id, in registry order. */',
    `export const CAPABILITY_IDS: readonly CapabilityId[] = [${capabilityIds.map(quote).join(', ')}]`,
    '',
    '/**',
    ' * Whether a string off the wire names a declared capability.',
    ' *',
    ' * A predicate rather than a lookup, so a value read out of a snapshot is',
    ' * narrowed by the compiler and never asserted into a capability it was',
    ' * only hoped to be.',
    ' * @param value - the name to read.',
    ' * @returns whether the name is one the registry declared.',
    ' */',
    'export function isCapabilityId(value: string): value is CapabilityId {',
    '  switch (value) {',
    ...capabilityIds.map((id) => `    case ${quote(id)}:`),
    '      return true',
    '    default:',
    '      return false',
    '  }',
    '}',
    '',
    '/**',
    ' * The actions seated in one placement, in registry order.',
    ' * @param placement - the surface to read.',
    ' * @returns the actions seated there.',
    ' */',
    'export function actionsInPlacement(placement: PlacementId): readonly ActionDescriptor[] {',
    '  return ACTION_LIST.filter((action) => action.placement === placement)',
    '}',
    '',
    '/**',
    ' * The actions one capability pays for.',
    ' * @param capability - the capability to read.',
    ' * @returns the actions that cost it.',
    ' */',
    'export function actionsForCapability(capability: CapabilityId): readonly ActionDescriptor[] {',
    '  return ACTION_LIST.filter((action) => action.capability === capability)',
    '}',
    '',
  ].join('\n')}\n`
}

/**
 * Emit the native boundary's route table.
 * @param registry - the validated registry.
 * @returns the contents of `apps/deeptail/src-tauri/src/capability/catalog.rs`.
 */
export function emitRust(registry: Registry): string {
  const routes = registry.actions.filter((action) => action.remote !== undefined)
  const routeLines = routes.map(
    (action) => `    RouteCapability { route: "${action.remote ?? ''}", capability: "${action.capability}" },`,
  )
  const ttlLines = registry.capabilities.map((row) => `    ("${row.id}", ${String(row.ttlSeconds)}),`)
  return `${[
    `//! ${BANNER}`,
    '//!',
    '//! The native half reads this table before it carries a call. A route the page',
    '//! holds no live grant for is refused here before it reaches the host, so the',
    '//! webview cannot spend a capability the native authority has not issued, and',
    '//! cannot reach a route no action names.',
    '',
    '/// One remote route and the capability it costs.',
    'pub struct RouteCapability {',
    '    /// The `namespace/method` the page asked for.',
    '    pub route: &\'static str,',
    '    /// The capability the page must hold a live grant of.',
    '    pub capability: &\'static str,',
    '}',
    '',
    '/// Every route the registry reaches, and what it costs.',
    'pub const ROUTE_CAPABILITIES: &[RouteCapability] = &[',
    ...routeLines,
    '];',
    '',
    '/// How long an issued grant of each capability stays spendable, in seconds.',
    'pub const CAPABILITY_TTLS: &[(&str, u64)] = &[',
    ...ttlLines,
    '];',
    '',
    '/// The capability one route costs, or None when no action reaches it.',
    'pub fn capability_for_route(route: &str) -> Option<&\'static str> {',
    '    ROUTE_CAPABILITIES',
    '        .iter()',
    '        .find(|entry| entry.route == route)',
    '        .map(|entry| entry.capability)',
    '}',
    '',
    '/// How long a grant of one capability lasts, or None when it is undeclared.',
    'pub fn ttl_for_capability(capability: &str) -> Option<u64> {',
    '    CAPABILITY_TTLS',
    '        .iter()',
    '        .find(|(id, _)| *id == capability)',
    '        .map(|(_, ttl)| *ttl)',
    '}',
    '',
  ].join('\n')}\n`
}
