/**
 * The page's typed face, emitted.
 *
 * Two faces come out of one registry. The page compiles against a typed
 * descriptor per action, so a control builder cannot be handed an id nothing
 * declared and a label key cannot name a dictionary entry that does not exist.
 * The native boundary compiles against a route table, so the Rust half prices
 * every remote call in the same capabilities the page spends, from the same
 * bytes.
 *
 * Both are generated, both carry the banner of what wrote them, and a suite
 * regenerates them and compares bytes, so a hand edit is a failing test rather
 * than a silent divergence.
 *
 * @module
 */

import type { ActionRow, Registry } from './action-registry.ts'
import { AVAILABILITY } from './action-registry.ts'

/** The header every generated file carries, naming what wrote it. */
export const BANNER = 'Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.'

/**
 * Quote one value for the emitted source.
 * @param value - the string to quote.
 * @returns a single-quoted literal.
 */
function quote(value: string): string {
  return `'${value.replaceAll("'", "\\'")}'`
}

/**
 * The union type one list of names becomes.
 * @param names - the names, in document order.
 * @returns the union, wrapped onto lines when it is long.
 */
function union(names: readonly string[]): string {
  const parts = names.map((name) => quote(name))
  const oneLine = ` ${parts.join(' | ')}`
  return oneLine.length <= 97 ? oneLine : `\n${parts.map((part) => `  | ${part}`).join('\n')}`
}

/**
 * One array literal, wrapped onto lines when it will not sit on one.
 * @param declaration - everything up to and including the `=`.
 * @param items - the elements, already rendered as source.
 * @returns the declaration.
 */
function array(declaration: string, items: readonly string[]): string {
  const oneLine = `${declaration} [${items.join(', ')}]`
  if (oneLine.length <= 120) return oneLine
  return `${declaration} [\n${items.map((item) => `  ${item},`).join('\n')}\n]`
}

/**
 * One action as the emitted object literal.
 * @param action - the row.
 * @returns the entry, with its trailing comma.
 */
function emitAction(action: ActionRow): string {
  const fields = [
    `id: ${quote(action.id)}`,
    `capability: ${quote(action.capability)}`,
    `placement: ${quote(action.placement)}`,
    `kind: ${quote(action.kind)}`,
    `pane: ${quote(action.pane)}`,
    `marker: ${quote(action.marker)}`,
    `availability: ${quote(action.availability)}`,
  ]
  if (action.labelKey !== undefined) fields.push(`labelKey: ${quote(action.labelKey)}`)
  if (action.labelKeyOn !== undefined) fields.push(`labelKeyOn: ${quote(action.labelKeyOn)}`)
  if (action.remote !== undefined) fields.push(`remote: ${quote(action.remote)}`)
  return `  ${quote(action.id)}: {\n${fields.map((field) => `    ${field}`).join(',\n')},\n  },`
}

/**
 * The header every emitted module opens with.
 * @param what - one sentence saying what this module holds.
 * @returns the doc comment, as lines.
 */
function header(what: string): string[] {
  return [
    `/**\n * ${BANNER}\n *`,
    ` * ${what}`,
    ' *',
    ' * Do not edit. The suite that regenerates this file from the registry fails',
    ' * when the two disagree, so the only way to change what lives here is to',
    ' * change the registry and regenerate.',
    ' * @module',
    ' */',
    '',
  ]
}

/**
 * The names the page compiles against, as union types.
 * @param registry - the validated registry.
 * @returns the type declarations.
 */
function emitNames(registry: Registry): string[] {
  return [
    `type PlacementId =${union(registry.placements.map((row) => row.id))}`,
    '',
    `export type ActionId =${union(registry.actions.map((row) => row.id))}`,
    '',
    `export type ActionMarker =${union(registry.actions.map((row) => row.marker))}`,
    '',
    `type AvailabilityId = ${AVAILABILITY.map((name) => quote(name)).join(' | ')}`,
    '',
    "type ActionKind = 'query' | 'mutation' | 'navigation' | 'toggle' | 'dialog'",
    '',
    "type ActionPane = 'main' | 'sheet' | 'menu' | 'drawer' | 'none'",
  ]
}

/**
 * The descriptor every action is read through.
 * @returns the interface declaration.
 */
function emitActionDescriptor(): string[] {
  return [
    '/** One declared action, in full. */',
    'export interface ActionDescriptor {',
    '  readonly id: ActionId',
    '  readonly capability: CapabilityId',
    '  readonly placement: PlacementId',
    '  readonly kind: ActionKind',
    '  readonly pane: ActionPane',
    '  /** The `data-deeptail-action` the control carries, which the suites drive it by. */',
    '  readonly marker: ActionMarker',
    '  /** The predicate that decides whether the control is drawn at all. */',
    '  readonly availability: AvailabilityId',
    '  /** The dictionary key naming the control, absent when its name comes from the row it sits on. */',
    '  readonly labelKey?: PickerKey',
    '  /** The key a toggle carries while it is on. */',
    '  readonly labelKeyOn?: PickerKey',
    '  /** The remote route the action reaches, which the native boundary prices in capabilities. */',
    '  readonly remote?: string',
    '}',
  ]
}

/**
 * Emit the capability half of the page's face.
 *
 * Its own module because the table of actions is long enough that holding both
 * in one file put it past the size a source file here may reach — and because
 * what a capability is is a smaller question than what an action is.
 * @param registry - the validated registry.
 * @returns the contents of `apps/deeptail/src/actions/capabilities.ts`.
 */
export function emitCapabilities(registry: Registry): string {
  const capabilityIds = registry.capabilities.map((row) => row.id)
  return `${[
    ...header('Every capability the registry declares, and how long a grant of one lasts.'),
    `export type CapabilityId =${union(capabilityIds)}`,
    '',
    "type SubjectKind = 'device' | 'host'",
    '',
    '/** One declared capability, and how long a grant of it stays spendable. */',
    'export interface CapabilityDescriptor {',
    '  readonly id: CapabilityId',
    '  readonly subject: SubjectKind',
    '  readonly ttlSeconds: number',
    '}',
    '',
    '/** Every declared capability, by id. */',
    'export const CAPABILITIES: Record<CapabilityId, CapabilityDescriptor> = {',
    ...registry.capabilities.map(
      (row) =>
        `  ${quote(row.id)}: { id: ${quote(row.id)}, subject: ${quote(row.subject)}, ttlSeconds: ${String(row.ttlSeconds)} },`,
    ),
    '}',
    '',
    '/**',
    ' * Whether a string off the wire names a declared capability.',
    ' *',
    ' * A predicate rather than a lookup, so a value read out of a snapshot is',
    ' * narrowed by the compiler and never asserted into a capability it was',
    ' * only hoped to be.',
    ' * @param value - the name to read.',
    ' * @returns whether the name is one the registry declared.',
    ' */',
    'export function isCapabilityId(value: string): value is CapabilityId {',
    '  switch (value) {',
    ...capabilityIds.map((id) => `    case ${quote(id)}:`),
    '      return true',
    '    default:',
    '      return false',
    '  }',
    '}',
  ].join('\n')}\n`
}

/**
 * Emit the table of actions.
 *
 * Its own module because it is by far the longest thing the registry produces,
 * and the types it is written in terms of are what everything else reads.
 * @param registry - the validated registry.
 * @returns the contents of `apps/deeptail/src/actions/action-table.ts`.
 */
export function emitActionTable(registry: Registry): string {
  return `${[
    ...header('Every action the registry declares, by id.'),
    "import type { ActionDescriptor, ActionId } from './registry.ts'",
    '',
    '/** Every declared action, by id. */',
    'export const ACTIONS: Record<ActionId, ActionDescriptor> = {',
    ...registry.actions.map((row) => emitAction(row)),
    '}',
  ].join('\n')}\n`
}

/**
 * Emit the page's typed face.
 * @param registry - the validated registry.
 * @returns the contents of `apps/deeptail/src/actions/registry.ts`.
 */
export function emitTypeScript(registry: Registry): string {
  const actionIds = registry.actions.map((row) => row.id)
  return `${[
    ...header('The types every action is read through, and the lists that walk them.'),
    "import type { PickerKey } from '../locales.ts'",
    "import { ACTIONS } from './action-table.ts'",
    "import type { CapabilityId } from './capabilities.ts'",
    '',
    "export { ACTIONS } from './action-table.ts'",
    "export type { CapabilityId } from './capabilities.ts'",
    "export { CAPABILITIES, isCapabilityId } from './capabilities.ts'",
    '',
    ...emitNames(registry),
    '',
    ...emitActionDescriptor(),
    '',
    '/** Every declared action, in registry order. */',
    array(
      'export const ACTION_LIST: readonly ActionDescriptor[] =',
      actionIds.map((id) => `ACTIONS[${quote(id)}]`),
    ),
    '',
    '/** Every declared action id, in registry order. */',
    array(
      'export const ACTION_IDS: readonly ActionId[] =',
      actionIds.map((id) => quote(id)),
    ),
  ].join('\n')}\n`
}
