//! Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.
//!
//! The native half reads this table before it carries a call. A route named
//! here is refused unless the page holds a live grant the native authority
//! issued, so the webview cannot spend a capability it was never given.
//!
//! A route not named here is one no DeepTail action reaches. Those are the
//! harness client's own calls, which it makes for itself once it has booted,
//! and they are carried unpriced: this table prices the control plane, not
//! the client that the control plane hands the page to.

/// Whose authority a grant of a capability carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Subject {
    /// One grant covers this installation.
    Device,
    /// One grant covers exactly one paired host.
    Host,
}

/// One remote route and the capability it costs.
pub struct RouteCapability {
    /// The `namespace/method` the page asked for.
    pub route: &'static str,
    /// The capability the page must hold a live grant of.
    pub capability: &'static str,
}

/// One declared capability, and how a grant of it is scoped and aged.
pub struct CapabilityDescriptor {
    pub id: &'static str,
    pub subject: Subject,
    pub ttl_seconds: u64,
}

/// Every route the registry reaches, and what it costs.
pub const ROUTE_CAPABILITIES: &[RouteCapability] = &[
    RouteCapability { route: "session/list", capability: "session.open" },
    RouteCapability { route: "session/cancel", capability: "session.cancel" },
    RouteCapability { route: "session/prompt", capability: "session.message" },
    RouteCapability { route: "session/create", capability: "session.create" },
];

/// Every capability the registry declares.
pub const CAPABILITIES: &[CapabilityDescriptor] = &[
    CapabilityDescriptor { id: "host.read", subject: Subject::Device, ttl_seconds: 900 },
    CapabilityDescriptor { id: "host.pair", subject: Subject::Device, ttl_seconds: 300 },
    CapabilityDescriptor { id: "host.forget", subject: Subject::Host, ttl_seconds: 300 },
    CapabilityDescriptor { id: "host.select", subject: Subject::Device, ttl_seconds: 3600 },
    CapabilityDescriptor { id: "session.read", subject: Subject::Host, ttl_seconds: 300 },
    CapabilityDescriptor { id: "session.create", subject: Subject::Host, ttl_seconds: 120 },
    CapabilityDescriptor { id: "session.message", subject: Subject::Host, ttl_seconds: 120 },
    CapabilityDescriptor { id: "session.cancel", subject: Subject::Host, ttl_seconds: 120 },
    CapabilityDescriptor { id: "session.open", subject: Subject::Host, ttl_seconds: 600 },
    CapabilityDescriptor { id: "tailnet.read", subject: Subject::Device, ttl_seconds: 300 },
    CapabilityDescriptor { id: "tailnet.connect", subject: Subject::Device, ttl_seconds: 300 },
    CapabilityDescriptor { id: "tailnet.forget", subject: Subject::Device, ttl_seconds: 300 },
    CapabilityDescriptor { id: "shell.navigate", subject: Subject::Device, ttl_seconds: 3600 },
];

/// The capability one route costs, or None when no action reaches it.
pub fn capability_for_route(route: &str) -> Option<&'static str> {
    ROUTE_CAPABILITIES
        .iter()
        .find(|entry| entry.route == route)
        .map(|entry| entry.capability)
}

/// One declared capability, or None when it is undeclared.
pub fn descriptor(capability: &str) -> Option<&'static CapabilityDescriptor> {
    CAPABILITIES.iter().find(|entry| entry.id == capability)
}

