//! Generated by scripts/gen-action-registry.ts from apps/deeptail/src/actions/actions.bao.
//!
//! The native half reads this table before it carries a call. A route the page
//! holds no live grant for is refused here before it reaches the host, so the
//! webview cannot spend a capability the native authority has not issued, and
//! cannot reach a route no action names.

/// One remote route and the capability it costs.
pub struct RouteCapability {
    /// The `namespace/method` the page asked for.
    pub route: &'static str,
    /// The capability the page must hold a live grant of.
    pub capability: &'static str,
}

/// Every route the registry reaches, and what it costs.
pub const ROUTE_CAPABILITIES: &[RouteCapability] = &[
    RouteCapability { route: "session/list", capability: "session.open" },
    RouteCapability { route: "session/cancel", capability: "session.cancel" },
    RouteCapability { route: "session/prompt", capability: "session.message" },
    RouteCapability { route: "session/prompt", capability: "session.message" },
    RouteCapability { route: "session/create", capability: "session.create" },
];

/// How long an issued grant of each capability stays spendable, in seconds.
pub const CAPABILITY_TTLS: &[(&str, u64)] = &[
    ("host.read", 900),
    ("host.pair", 300),
    ("host.forget", 300),
    ("host.select", 3600),
    ("session.read", 300),
    ("session.create", 120),
    ("session.message", 120),
    ("session.cancel", 120),
    ("session.open", 600),
    ("tailnet.read", 300),
    ("tailnet.connect", 300),
    ("tailnet.forget", 300),
    ("shell.navigate", 3600),
];

/// The capability one route costs, or None when no action reaches it.
pub fn capability_for_route(route: &str) -> Option<&'static str> {
    ROUTE_CAPABILITIES
        .iter()
        .find(|entry| entry.route == route)
        .map(|entry| entry.capability)
}

/// How long a grant of one capability lasts, or None when it is undeclared.
pub fn ttl_for_capability(capability: &str) -> Option<u64> {
    CAPABILITY_TTLS
        .iter()
        .find(|(id, _)| *id == capability)
        .map(|(_, ttl)| *ttl)
}

